### ISSUE TITLE
Version 1.16.5

### ISSUE THREAD

**Issue by Waffle02** [yakovliam-com/DeluxeChatHex#1]
https://pastebin.com/Aef2eR6K getting this error

**Comment by yakovliam** [comment]
What do your chat formats look like (or the one in question during the time that the error occurred)?

**Comment by Waffle02** [comment]
I get the same error every time I send any message in chat. This is my deluxechat config for the chat format https://pastebin.com/G6sbW6Xm

**Comment by yakovliam** [comment]
Please join the [HelpChat](https://helpch.at/discord) discord so we can talk in real-time to debug the issue and fix it.
