### ISSUE TITLE
Hex codes return default Minecraft colours

### ISSUE THREAD

**Issue by ConstructorLeo** [yakovliam-com/DeluxeChatHex#2]
Hi there,

I'm trying to setup hex codes in DeluxeChat. The server is running Airplane 1.16.5 with the latest Spigot version of DeluxeChat, 1.16.2, however, the hex codes show up as a default Minecraft colour instead of the colour it should return as.

Some ranks are different colours, the two below are black and white for whatever reason.

![image](https://user-images.githubusercontent.com/7409865/133549991-555df2e0-75fb-45a6-9393-c67e08e0c49f.png)

Everytime somebody talks, this error is sent:

![image](https://user-images.githubusercontent.com/7409865/133550936-f2d90ef9-7235-4b6a-b7a0-09734da9eba2.png)

**Comment by ConstructorLeo** [comment]
Looks like some hex codes work, others don't. This one does:
![image](https://user-images.githubusercontent.com/7409865/133551942-d8a6e904-e81f-46f9-9366-a3b4c8d4e571.png)

**Comment by yakovliam** [comment]
Feel free to open up a new issue / reopen etc if this persists (solved in DMs with a new build).
